- name: Configure All Homelab Hosts
  hosts: all
  become: yes
  gather_facts: yes
  
  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300
    
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
    - name: Upgrade system packages
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"

  roles:
    - common
    - security

- name: Configure Pi-hole Servers
  hosts: pihole
  become: yes
  gather_facts: yes
  
  roles:
    - pihole

- name: Configure Docker Hosts
  hosts: docker_hosts
  become: yes
  gather_facts: yes
  
  roles:
    - docker
    - monitoring